<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Name-&amp;-ID" data-toc-modified-id="Name-&amp;-ID-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Name &amp; ID</a></span></li><li><span><a href="#Problem-#-A" data-toc-modified-id="Problem-#-A-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Problem # A</a></span><ul class="toc-item"><li><span><a href="#A-1" data-toc-modified-id="A-1-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>A-1</a></span></li><li><span><a href="#A-2" data-toc-modified-id="A-2-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>A-2</a></span></li><li><span><a href="#A-3" data-toc-modified-id="A-3-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>A-3</a></span></li><li><span><a href="#A-4" data-toc-modified-id="A-4-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>A-4</a></span></li><li><span><a href="#A-5" data-toc-modified-id="A-5-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>A-5</a></span></li><li><span><a href="#A-6" data-toc-modified-id="A-6-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>A-6</a></span></li><li><span><a href="#A-7" data-toc-modified-id="A-7-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>A-7</a></span></li><li><span><a href="#A-8" data-toc-modified-id="A-8-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>A-8</a></span></li><li><span><a href="#A-9" data-toc-modified-id="A-9-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>A-9</a></span></li></ul></li><li><span><a href="#Problem-#-B" data-toc-modified-id="Problem-#-B-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Problem # B</a></span><ul class="toc-item"><li><span><a href="#B-1" data-toc-modified-id="B-1-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>B-1</a></span></li><li><span><a href="#B-2" data-toc-modified-id="B-2-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>B-2</a></span></li><li><span><a href="#B-3" data-toc-modified-id="B-3-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>B-3</a></span></li><li><span><a href="#B-4" data-toc-modified-id="B-4-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>B-4</a></span></li><li><span><a href="#B-5" data-toc-modified-id="B-5-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>B-5</a></span></li><li><span><a href="#B-6" data-toc-modified-id="B-6-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>B-6</a></span></li><li><span><a href="#B-7" data-toc-modified-id="B-7-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>B-7</a></span></li><li><span><a href="#B-8" data-toc-modified-id="B-8-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>B-8</a></span></li></ul></li><li><span><a href="#Problem-C" data-toc-modified-id="Problem-C-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Problem C</a></span><ul class="toc-item"><li><span><a href="#C-2" data-toc-modified-id="C-2-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>C-2</a></span></li><li><span><a href="#C-3" data-toc-modified-id="C-3-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>C-3</a></span></li><li><span><a href="#C-4" data-toc-modified-id="C-4-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>C-4</a></span></li><li><span><a href="#Rough-Work" data-toc-modified-id="Rough-Work-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Rough Work</a></span></li></ul></li></ul></div>

# Name & ID

In [ ]:
Name= 'Faisal Alhamdi'    #write your name

In [ ]:
ID= 202173830             #write your student ID

In [ ]:
# Execute this cell 
try:
    if (Name== 'First_Name  Last_Name')  | (ID== 202012345):
        raise ValueError('''
    **************************MISSING INFO*****************************
    Enter your name & student ID in the top cells (& execute the cells)
    *******************************************************************''') 
except:
    raise ValueError('''
    **************************MISSING INFO*****************************
    Enter your name & student ID in the top cells (& execute the cells)
    *******************************************************************''')
else:
    print('All set, you can proceed!')

# Problem # A

## A-1

In [ ]:
# Answers to A-1
import pandas as pd

df = pd.read_csv('C:/Users/Faisal/Downloads/HW#02/HW#02/HW2_DataA.csv', delimiter=',')
display(df.sample(10))
display(df.tail(10))

## A-2

In [ ]:
# Answers to A-2
import pandas as pd

ndf = df.iloc[0:20,1:6]
ndf.sort_values(by=['Days_for_shipment','Sales_per_customer'], inplace=True, ascending=[False, True])

## A-3

In [ ]:
# Answers to A-3
display(ndf.describe())
cat_columns= ndf.select_dtypes(include='object').columns
display(ndf[cat_columns].describe())

## A-4

In [ ]:
# Answers to A-4
import pandas as pd
newDf = pd.read_csv('C:/Users/Faisal/Downloads/HW#02/HW#02/HW2_DataA.csv', delimiter=',')

seleted_rows = (newDf['Shipping_Mode']=='First Class') & (newDf['Customer_Age']<=40) & (newDf['Product_Name']=='Smart watch')

print(len(newDf.loc[seleted_rows,:]))

## A-5

In [ ]:
# Answers to A-5

def custom_method(x):
    return (round(x))

import pandas as pd
df = pd.read_csv('C:/Users/Faisal/Downloads/HW#02/HW#02/HW2_DataA.csv', delimiter=',')
df.loc[:,'Order_Item_Discount_New']=df.loc[:,'Order_Item_Discount'].apply(custom_method)

## A-6

In [ ]:
# Answers to A-6
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure()
sns.histplot(x='Shipping_Mode',hue='Late_delivery',data=df);
plt.show()

## A-7

In [ ]:
# Answers to A-7
seleted_rows = (df['Order_Item_Discount']/df['Product_Price'])>0.3
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
sns.scatterplot(x=df.loc[seleted_rows,'Order_Item_Discount'], y='Sales_per_customer',  alpha=0.5, data=df)
plt.ylabel("Sales_per_customer");
plt.xlabel("Order_Item_Discount");
plt.title("Order_Item_Discount greater relationship to  Sales_per_customer");
plt.show()

print("conclustion: the relation between them is linear; if discount price increase then sales increase")

## A-8

In [ ]:
# Answers to A-8
plt.figure()
#     sns.histplot(y=c,data=df);
sns.countplot(y='Customer_Segment',hue='Type_of_Payment',data=df);
plt.show()

print("answer to i is: Consumer")
print("answer to ii is: Home Office")
print("answer to iii is: Debit because two of the three segment has it as the most prefered method and the third has it as the second")

## A-9

In [ ]:
# Answers to A-9

selected_rows = ((df['Order_Status']=='COMPLETE')|(df['Order_Status']=='PENDING'))& (df['Product_Name']=='Smart watch')

plt.figure()
sns.boxplot(y= df.loc[selected_rows,'Sales_per_customer'],x=df.loc[finished_rows,'Order_Status'],data=df);
plt.show()

print("the number of sales per customer depend on the type of order status and the pending orders median is more than the complete orders")

# Problem # B

## B-1

In [29]:
# Answers to B-1
import pandas as pd
df = pd.read_csv('C:/Users/Faisal/Downloads/HW#02/HW#02/HW2_DataB.csv', delimiter=',')
display(df)
print(f'The number of rows are {len(df.index)}, and the number of columns are {len(df.columns)}')
print("yes column (has_kids) have nulls")

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,has_kids
0,9046,Male,0.67,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,1.0
1,51676,Female,61.00,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1,1.0
2,31112,Male,80.00,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,1.0
3,60182,Female,49.00,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,1.0
4,1665,Female,79.00,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.00,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0,1.0
5106,44873,Female,81.00,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0,1.0
5107,19723,Female,35.00,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0,NaN
5108,37544,Male,51.00,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,1.0
5109,44679,Female,44.00,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0,NaN

The number of rows are 5110, and the number of columns are 13
yes column (has_kids) have nulls

## B-2

In [30]:
# Answers to B-2
display(df.info())
print("has kids have null and age is float")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5104 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5101 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
 12  has_kids           2790 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 519.1+ KB

None

has kids have null and age is float

## B-3

In [31]:
# Answers to B-3
df.loc[:,'age']=df.loc[:,'age'].apply(lambda x: int(x*100) if x<0 else int(x))
print(df.select_dtypes("object").describe().loc['unique', :])

df['gender'].unique().tolist()

index_row = df[ df['gender'] == 'Other' ].index
df.drop(index_row , inplace=True)


uniqueEducation=df['gender'].unique().tolist()


print(uniqueEducation)

gender            3
ever_married      2
work_type         5
Residence_type    2
smoking_status    4
Name: unique, dtype: object
['Male', 'Female']

## B-4

In [34]:
# Answers to B-4
df.dropna(axis=1 , how='any', thresh=df.shape[0]*.7,inplace=True)
display(df.info())
nulls=df.columns[df.isna().any()]
for i in nulls:
    if df[i].dtype!="object":
        val=df[i].mean()
    else:
        val=df[i].mode()
        val=val[0]
    df[i].fillna(val,inplace=True)
display(df)
nulls=df.columns[df.isna().any()]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5109 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5109 non-null   int64
 1   gender             5109 non-null   object
 2   age                5109 non-null   int64
 3   hypertension       5109 non-null   int64
 4   heart_disease      5109 non-null   int64
 5   ever_married       5109 non-null   object
 6   work_type          5109 non-null   object
 7   Residence_type     5109 non-null   object
 8   avg_glucose_level  5109 non-null   float64
 9   bmi                4908 non-null   float64
 10  smoking_status     5109 non-null   object
 11  stroke             5109 non-null   int64
dtypes: float64(2), int64(5), object(5)
memory usage: 518.9+ KB

None

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,0,0,1,Yes,Private,Urban,228.69,36.60000,formerly smoked,1
1,51676,Female,61,0,0,Yes,Self-employed,Rural,202.21,28.89456,never smoked,1
2,31112,Male,80,0,1,Yes,Private,Rural,105.92,32.50000,never smoked,1
3,60182,Female,49,0,0,Yes,Private,Urban,171.23,34.40000,smokes,1
4,1665,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.00000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80,1,0,Yes,Private,Urban,83.75,28.89456,never smoked,0
5106,44873,Female,81,0,0,Yes,Self-employed,Urban,125.20,40.00000,never smoked,0
5107,19723,Female,35,0,0,Yes,Self-employed,Rural,82.99,30.60000,never smoked,0
5108,37544,Male,51,0,0,Yes,Private,Rural,166.29,25.60000,formerly smoked,0
5109,44679,Female,44,0,0,Yes,Govt_job,Urban,85.28,26.20000,Unknown,0

## B-5

In [40]:
# Answers to B-5
from sklearn.preprocessing import StandardScaler
scaler1 = StandardScaler()
selected_collumns=df.select_dtypes(exclude='object')
scaler1.fit(selected_collumns)
selected_collumns = scaler1.transform(selected_collumns)
print(selected_collumns)

[[-1.29811278e+00 -1.90711170e+00 -3.28637494e-01 ...  2.70644995e+00
   1.00103390e+00  4.41792624e+00]
 [ 7.16543439e-01  7.86383996e-01 -3.28637494e-01 ...  2.12165168e+00
   1.38462701e-15  4.41792624e+00]
 [-2.55293073e-01  1.62534167e+00 -3.28637494e-01 ... -4.86741416e-03
   4.68392163e-01  4.41792624e+00]
 ...
 [-7.93527174e-01 -3.61663348e-01 -3.28637494e-01 ... -5.11265616e-01
   2.21558189e-01 -2.26350542e-01]
 [ 4.86775765e-02  3.44827325e-01 -3.28637494e-01 ...  1.32837547e+00
  -4.28004903e-01 -2.26350542e-01]
 [ 3.85871387e-01  3.57376558e-02 -3.28637494e-01 ... -4.60692049e-01
  -3.50057332e-01 -2.26350542e-01]]

## B-6

In [35]:
# Answers to B-6
from sklearn.preprocessing import LabelEncoder
encoder1=LabelEncoder()
encoder1.fit(df['work_type'])
df['work_type']=encoder1.transform(df['work_type'])
display(df)
print(f"n_values",df["work_type"].unique())

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,0,0,1,Yes,2,Urban,228.69,36.60000,formerly smoked,1
1,51676,Female,61,0,0,Yes,3,Rural,202.21,28.89456,never smoked,1
2,31112,Male,80,0,1,Yes,2,Rural,105.92,32.50000,never smoked,1
3,60182,Female,49,0,0,Yes,2,Urban,171.23,34.40000,smokes,1
4,1665,Female,79,1,0,Yes,3,Rural,174.12,24.00000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80,1,0,Yes,2,Urban,83.75,28.89456,never smoked,0
5106,44873,Female,81,0,0,Yes,3,Urban,125.20,40.00000,never smoked,0
5107,19723,Female,35,0,0,Yes,3,Rural,82.99,30.60000,never smoked,0
5108,37544,Male,51,0,0,Yes,2,Rural,166.29,25.60000,formerly smoked,0
5109,44679,Female,44,0,0,Yes,0,Urban,85.28,26.20000,Unknown,0

n_values [2 3 0 4 1]

## B-7

In [36]:
edu_mapping = {'No':0, 
               'Yes':1,}
df['ever_married'] = df['ever_married'].map(edu_mapping)
display(df)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,0,0,1,1,2,Urban,228.69,36.60000,formerly smoked,1
1,51676,Female,61,0,0,1,3,Rural,202.21,28.89456,never smoked,1
2,31112,Male,80,0,1,1,2,Rural,105.92,32.50000,never smoked,1
3,60182,Female,49,0,0,1,2,Urban,171.23,34.40000,smokes,1
4,1665,Female,79,1,0,1,3,Rural,174.12,24.00000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80,1,0,1,2,Urban,83.75,28.89456,never smoked,0
5106,44873,Female,81,0,0,1,3,Urban,125.20,40.00000,never smoked,0
5107,19723,Female,35,0,0,1,3,Rural,82.99,30.60000,never smoked,0
5108,37544,Male,51,0,0,1,2,Rural,166.29,25.60000,formerly smoked,0
5109,44679,Female,44,0,0,1,0,Urban,85.28,26.20000,Unknown,0

## B-8

In [ ]:
# Answers to B-8
print("when trying to change from words to numbers and have more than 2 words to describe the columnXrow variable")
print("it is a techniec used to manipulate and transform data gather and express data as summary in smaller variable and terms")
print("gather data from real world by talking to people and type it in file, indiriect use source to obtain the data needed")
print("a school students registation system that has all student in it, unstucterd a random sorted school registration system")
print("Variables that are measured at different scales do not equal to the model fitting and maybe create a problem ")

# Problem C

## C-2

In [ ]:
# Answer for C2
#Sex / nominal / M, F, and I (infant)
#Length / Longest shell measurement
#Diameter /  perpendicular to length
#Height /with meat in shell
#Whole weight /  whole abalone
#Shucked weight /weight of meat
#Viscera weight /  gut weight (after bleeding)
#Shell weight /after being dried
#Rings / integer that gives the age in years

## C-3

In [41]:
# Answers to C-3
import pandas as pd
headers=["sex","length","diameter","height","whole_weight","shucked_weight","viscera_weight","shell","rings"]
df = pd.read_csv('C:/Users/Faisal/Downloads/HW#02/HW#02/abalone.data', delimiter=',',header=None,names=headers)
display(df)

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

## C-4

In [43]:
# Answers to C-4
display(df.describe())

cat_columns= df.select_dtypes(include='object').columns
display(df[cat_columns].describe())

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell,rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

         sex
count   4177
unique     3
top        M
freq    1528

## Rough Work